# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170909_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=1, upload_to='profile_photo/'),
            preserve_default=False,
        ),
    ]
