# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170920_1544'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
