# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 15:03
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20170920_1725'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('upm', django.db.models.manager.Manager()),
            ],
        ),
    ]
