# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 07:28
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20170923_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
