# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20170923_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
