# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
