# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30)),
                ('city_pin_start', models.IntegerField()),
                ('city_pin_end', models.IntegerField()),
            ],
        ),
    ]
