# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiqourApp', '0003_userlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
