# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiqourApp', '0004_delete_userlocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
