# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiqourApp', '0005_auto_20170908_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='userId',
            new_name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
