# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiqourApp', '0006_auto_20170908_2104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
